export const products = [
    {
        coverImage: "./assets/img/phone-cover.jpg",
        name: 'Phone XL',
        price: '799',
        description: 'A large phone with one of the best screens',
        heding1: 'サンプルテキスト１',
        heding2: 'サンプルテキスト２',
        heding3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト　サンプルテキスト',
        headingtext2: 'テキスト文章　テキスト文章',
        headingtext3: 'Duis mllis, est non commodo luctus',
    },
    {
        coverImage: "./assets/img/phone-cover.jpg",
        name: 'Phone Mini',
        price: '699',
        description: 'A great phone with one of the best cameras',
        heding1: 'サンプルテキスト１',
        heding2: 'サンプルテキスト２',
        heding3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト　サンプルテキスト',
        headingtext2: 'テキスト文章　テキスト文章',
        headingtext3: 'Duis mllis, est non commodo luctus',
    },
    {
        coverImage: "./assets/img/phone-cover.jpg",
        name: 'Phone Standard',
        price: '299',
        description: '',
        heding1: 'サンプルテキスト１',
        heding2: 'サンプルテキスト２',
        heding3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト　サンプルテキスト',
        headingtext2: 'テキスト文章　テキスト文章',
        headingtext3: 'Duis mllis, est non commodo luctus',
    },
];
